Write scripts for autotesters on CI/CD

diff --git a/.github/workflows/mac_build_and_autotester.yml b/.github/workflows/mac_build_and_autotester.yml
--- a/.github/workflows/mac_build_and_autotester.yml
+++ b/.github/workflows/mac_build_and_autotester.yml
@@ -46,17 +46,82 @@ jobs:
         shell: bash
         working-directory: ${{ env.BUILD_DIR }}
         env:
-          CC: ${{ matrix.cc-compilers }}
-          CXX: ${{ matrix.cxx-compilers }}
+            CC: ${{ matrix.cc-compilers }}
+            CXX: ${{ matrix.cxx-compilers }}
         run: |
             cmake --build . --config ${{ matrix.build-type }} -j 4
             cmake --build . --target autotester --config ${BUILD_TYPE} -j 4
 
-      - name: Run Autotester
+      - name: Run Autotester on Milestone 1
+        shell: bash
         working-directory: ${{ env.AUTOTESTER_M1_DIR }}
         run: |
-            chmod +x run_test.sh
-            ./run_test.sh
+            mkdir -p logs outputs
+            echo "[System Test] Running all tests for Milestone 1"
+            EXIT_CODE="0"
+
+            for file in source/*_source.txt; do
+                # shellcheck disable=SC2001
+                test_name=$(echo "$file" | sed 's|.*/\(.*\)_source\.txt$|\1|') # regex generated with aid of ChatGPT
+                echo "[System Test] Running Test: $test_name"
+                ${{ env.TEST_DIR }}/autotester "$file" queries/"$test_name"_queries.txt outputs/"$test_name"_output.xml > logs/log_"$test_name".txt
+                echo "[System Test] Test $test_name complete"
+                if [ "$?" != 0 ]; then
+                echo "[System Test] Test $test_name has failed"
+                EXIT_CODE="1"
+                else
+                echo "[System Test] Test $test_name succeed"
+                head -1 logs/log_"$test_name".txt
+                FILENAME=outputs/"$test_name"_output.xml
+                QUERIES=$(grep -o '</query>' "$FILENAME" | wc -l)
+                PASSES=$(grep -o '<passed/>' "$FILENAME" | wc -l)
+                FAILS=$(grep -c '</failed>' "$FILENAME" || echo "0")
+                EXCEPTIONS=$(grep -c '<exception/>' "$FILENAME" || echo "0")
+                echo "[System Test] Queries: $QUERIES; Passes: $PASSES; Fails: $FAILS; EXCEPTIONS: $EXCEPTIONS"
+                if [ "$QUERIES" != "$PASSES" ]; then
+                    echo "[Alert!] Some system tests have failed. Please try again!"
+                    EXIT_CODE="2"
+                fi
+                fi
+            done
+
+            exit $EXIT_CODE
+
+
+      - name: Run Autotester on Milestone 2
+        shell: bash
+        working-directory: ${{ env.AUTOTESTER_M2_DIR }}
+        run: |
+            mkdir -p logs outputs
+            echo "[System Test] Running all tests for Milestone 1"
+            EXIT_CODE="0"
+
+            for file in source/*_source.txt; do
+                # shellcheck disable=SC2001
+                test_name=$(echo "$file" | sed 's|.*/\(.*\)_source\.txt$|\1|') # regex generated with aid of ChatGPT
+                echo "[System Test] Running Test: $test_name"
+                ${{ env.TEST_DIR }}/autotester "$file" queries/"$test_name"_queries.txt outputs/"$test_name"_output.xml > logs/log_"$test_name".txt
+                echo "[System Test] Test $test_name complete"
+                if [ "$?" != 0 ]; then
+                echo "[System Test] Test $test_name has failed"
+                EXIT_CODE="1"
+                else
+                echo "[System Test] Test $test_name succeed"
+                head -1 logs/log_"$test_name".txt
+                FILENAME=outputs/"$test_name"_output.xml
+                QUERIES=$(grep -o '</query>' "$FILENAME" | wc -l)
+                PASSES=$(grep -o '<passed/>' "$FILENAME" | wc -l)
+                FAILS=$(grep -c '</failed>' "$FILENAME" || echo "0")
+                EXCEPTIONS=$(grep -c '<exception/>' "$FILENAME" || echo "0")
+                echo "[System Test] Queries: $QUERIES; Passes: $PASSES; Fails: $FAILS; EXCEPTIONS: $EXCEPTIONS"
+                if [ "$QUERIES" != "$PASSES" ]; then
+                    EXIT_CODE="2"
+                fi
+                fi
+            done
+
+            exit $EXIT_CODE
+
 
       - name: Cleanup Directory
         if: always()
