Add memory check

diff --git a/.github/workflows/window_build_and_autotester.yml b/.github/workflows/window_build_and_autotester.yml
--- a/.github/workflows/window_build_and_autotester.yml
+++ b/.github/workflows/window_build_and_autotester.yml
@@ -20,6 +20,7 @@ env:
     TEST_DIR: ${{ github.workspace }}/Team19/Code19/build/src/autotester
     AUTOTESTER_M1_DIR: ${{ github.workspace }}/Team19/Tests19/system_testing/m1
     AUTOTESTER_M2_DIR: ${{ github.workspace }}/Team19/Tests19/system_testing/m2
+    AUTOTESTER_M3_DIR: ${{ github.workspace }}/Team19/Tests19/system_testing/m3
 
 jobs:
   build_autotester_window:
@@ -95,6 +96,44 @@ jobs:
         working-directory: ${{ env.AUTOTESTER_M2_DIR }}
         run: |
             Write-Host "[System Test] Running all tests for Milestone 2"
+            $EXIT_CODE = 0
+            mkdir -p outputs
+            mkdir -p logs
+
+            foreach ($file in Get-ChildItem source/*_source.txt) {
+                Write-Host "Run test"
+                $test_name = ($file.Name -split "_source.txt")[0]  # Extract test name from file name
+                Write-Host "[System Test] Running Test: $test_name"
+                & ${{ env.TEST_DIR }}/${{ env.BUILD_TYPE }}/autotester.exe "source/${test_name}_source.txt" "queries/${test_name}_queries.txt" "outputs/${test_name}_output.xml" > "logs/log_${test_name}.txt"
+    
+                if ($LASTEXITCODE -ne 0) {
+                    $EXIT_CODE = 1
+                }
+                else {
+                    $firstLine = Get-Content "logs/log_${test_name}.txt" -First 1
+                    Write-Host $firstLine
+                    $FILENAME = "outputs/${test_name}_output.xml"
+                    $QUERIES = ((Get-Content $FILENAME) -match '</query>').Count
+                    $PASSES = ((Get-Content $FILENAME) -match '<passed/>').Count
+                    $FAILS = ((Get-Content $FILENAME) -match '</failed>').Count
+                    Write-Host "[System Test] Queries: $QUERIES; Passes: $PASSES; Fails: $FAILS"
+
+                    if ($QUERIES -ne $PASSES) {
+                        # This is commented out because the milestone 2 tests are not yet fully tested
+                        # Need to set exit code to 2 before submitting for M2
+                        $EXIT_CODE = 2
+                    }
+                }
+            }
+
+            exit $EXIT_CODE
+
+      # Run autotester tests for Milestone 3
+      - name: Run Autotester Tests in Milestone 3
+        shell: pwsh
+        working-directory: ${{ env.AUTOTESTER_M3_DIR }}
+        run: |
+            Write-Host "[System Test] Running all tests for Milestone 3"
             $EXIT_CODE = 0
             mkdir -p outputs
             mkdir -p logs
